### PR TITLE
Flexibus/#364/sportify project

### LINKED ISSUE #364: New name of project
New name of project is "SPORTIFY".
This name should be placed on every page in top right corner with logo. 

Like this:

The font is the same.
The font-size is 26px. 
"SPORTIFY" should be written with capital letters (no need to use graphics)

### PR DESCRIPTION
**Pull request by jkbe**
Closes #364

### CODE REVIEW

**Review by jonashering — COMMENTED** [review]
Guess it would make sense to change the project's name in `en.yml` as well?

**Comment by jonashering** [comment]
Just wondering: Sportify in the footer not in all caps is intended?

**Comment by jkbe** [comment]
Yup, no all caps in footer is according to specs.

**Comment by jkbe** [comment]
Please recheck @jonashering

**Review by jonashering — APPROVED** [review]
Looks all good to me 👍

**Pull request merged**
