### PR TITLE
Flexibus/i18n german localization

### PR DESCRIPTION
**Pull request by jonashering**
Change default language to German and add German locales as yamls. Request of POs.

Locales are taken from:
* `devise.de.yml`: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/de.yml
* `de.default.yml` : https://gist.github.com/thomasklemm/6821669
* `de.yml` and `de.helpers.yml` manually translated
(sources to links can also be found in files)

Note:
* Cucumber tests are currently set to English

### CODE REVIEW

**Comment by jkbe** [comment]
@hpi-swt2/scrum-masters for your information.

**Review by jkbe — APPROVED** [review]
Looks good to me!

**Comment by Askir** [comment]
Looks alright, although I'm not sure if we actually need the huge file with default translations it probably wont hurt. Also there are still a lot of spots where I18N isn't used yet but I hope that will be resolved in the next few weeks.

**Review by Askir — APPROVED** [review]

**Comment by jkbe** [comment]
We already have big files with default English phrases which we don't all use - so it doesn't really make a difference I guess. However, we will discuss this in more detail in the meeting of Scrum Masters on Friday.
I saw these places as well where i18n isn't used yet. It seams like the displayed fields etc. are coming straight from the DB schema...

**Pull request merged**
