### PR TITLE
Fix profile error translations. Ref #485

### LINKED ISSUE #485: translate profile creation errors to german
**As a** german user
**I want to** have german error messages while editing profile data
**In order to** unterstand the error messages I get while editing

### notes:
 * was part of #369 

## Acceptance Criteria
* [x] please germanize all Error messages, e.g. "Birthday Der Geburtstag darf nicht in der Zukunft liegen" or (2) or (3) 
* [x] please translate the Choose file / no file chosen (visible in (1)) as well

### pictures:
(1)
 image
(2)
image
(3)
image

### PR DESCRIPTION
**Pull request by fpottbaecker**
This will close #485.

Already reviewed and accepted by PO.

### CODE REVIEW

**Comment by ErikBrendel** [comment]
sounds pretty german to me :D
best nearly-german error message screenshot

**Comment by ErikBrendel** [comment]
Are reference picture (2) and (3) of the userstory both unfixable? What about "No file selected"?

**Comment by ErikBrendel** [comment]
What about the "missing avatar" error message when selecting a no-image-file as avatar picture?

**Review by DanielStephan97 — APPROVED** [review]

**Comment by DanielStephan97** [comment]
@ErikBrendel Could not reproduce any of your errors.

**Comment by fpottbaecker** [comment]
@ErikBrendel see the issue comment.

**Pull request merged**
