### PR TITLE
Make ApplicationMailer able to send e-mails via the configured SMTP server

### PR DESCRIPTION
**Pull request by bakoe**
See #462

### CODE REVIEW

**Review by jkbe — APPROVED** [review]
Please, split up these huge PRs in the future!

**Comment by nikriek** [comment]
Bye bye coverage

**Comment by nikriek** [comment]
Is that enough to fix the issue?

**Comment by jkbe** [comment]
Whoops, I approved just before the Travis Builds failed. Seems the Application Mailer needs some default so that the sender address is not `nil`. Just set it to the GMX Sport Portal address as well?

**Comment by bakoe** [comment]
@nikriek 
> Is that enough? 

It seems like it's enough – at least locally the e-mails can be sent via the GMX account now. 🙂

**Comment by bakoe** [comment]
@jak-ing 
> Just set it to the GMX Sport Portal address as well?

I'm on it. 👍

**Review by birneamstiel — APPROVED** [review]

**Pull request merged**
